- src/background/controller/wallet.ts
- src/background/service/openapi.ts
- src/background/service/preference.ts
1. fix balance cache can not be access if address has uppercase
2. not cache balance if address total value is 0
3. remove balance cache when address is removed
> chore: not cache balance if address total value is 0

- src/ui/views/Approval/components/SignTx.tsx
1. only exec security check when preprocess success
2. fix root scope  view raw is an array
> fix: only exec security check when preprocess success

- src/background/controller/provider/controller.ts
> feat: support personal_ecRecove

- src/background/controller/wallet.ts
- src/background/service/preference.ts
- src/background/utils/index.ts
- src/constants/index.ts
- src/ui/component/AddressList/AddressItem.tsx
- src/ui/component/AddressList/index.tsx
- src/ui/component/AddressList/style.less
- src/ui/views/Dashboard/style.less
- src/ui/views/ImportSuccess/index.tsx
- src/ui/views/ImportWatchAddress.tsx
1. Fix import overwrite alian name.
2. Fix Address management page, when edit input being focus, value turn to  empty.
3. Fix success imported, style not align middle.
> fix: not overwrite alian name when there is an exist one

- _raw/_locales/en/messages.json
Small typo: "your are" -> "you are"
> Fixing typo

- src/background/controller/provider/controller.ts
- src/constant/index.ts
- src/ui/views/Approval/components/SignTx.tsx
- src/utils/transaction.ts
Specification: https://debankglobal.larksuite.com/docs/docusCViclSYBSGfzjCtxQb0FFb
> feat: + gasPrice protection range

- src/constant/index.ts
https://twitter.com/gnosischain/status/1476878573151608836
> feat: rename xDai to Gnosis

- src/ui/views/Dashboard/components/RecentConnections/index.tsx
- src/ui/views/Dashboard/components/RecentConnections/style.less
fix web management popup style
> style: fix web management popup style

- src/ui/views/Dashboard/components/RecentConnections/ConnectionList.tsx
- src/ui/views/Dashboard/components/RecentConnections/index.tsx
> style: fix website management empty style

- src/ui/component/TokenAmountInput/index.tsx
- src/ui/component/TokenSelector/index.tsx
- src/ui/component/TokenSelector/style.less
- src/ui/style/antd-overwrite.less
1. Make close button of drawer bigger
2. Make TokenSearch case insensitive
3. Change border-color of input of TokenSelector
> fix: close button size of drawer

- src/content-script/pageProvider/index.ts
This PR fix the issue that may make some dapps(like curve.fi) not works with Rabby
You can download and unzip the attachment zip file and install it before we release the new version
Guide: https://stackoverflow.com/questions/9931906/crx-file-install-in-chrome
[Rabby-patch.crx.zip](https://github.com/RabbyHub/Rabby/files/7976601/Rabby-patch.crx.zip)
> fix: connection issue with curve

- package.json
- src/ui/views/ImportWatchAddress.tsx
- yarn.lock
> feat: use official bridge server as default walletconnect bridge server

- src/background/controller/provider/controller.ts
- src/background/service/preference.ts
i.e. validate text message sig failed in apy.vision
> feat: transfer address to lowercase when expose to dapp

- src/content-script/pageProvider/index.ts
> fix: response of isConnected should always be true

- _raw/_locales/en/messages.json
- _raw/_locales/zh_CN/messages.json
- src/ui/views/Approval/components/SecurityCheckDetail.tsx
> Fix typo when confirm transaction

- src/ui/views/Dashboard/style.less
> fix: make full switch address button responsive

- src/ui/views/SendNFT/index.tsx
- src/ui/views/SendToken/index.tsx
example: 
- https://sentry.io/organizations/debank/issues/3262217092/?project=5831390&query=is%3Aunresolved
- https://sentry.io/organizations/debank/issues/3262208901/?project=5831390&query=is%3Aunresolved
> feat: report token validation failed to Sentry

- src/ui/component/AddAddressOptions/Field/index.tsx
- src/ui/component/AddAddressOptions/Field/style.less
- src/ui/component/AddAddressOptions/index.tsx
- src/ui/component/AddAddressOptions/style.less
- src/ui/component/Field/index.tsx
- src/ui/style/index.less
- src/ui/views/Approval/style.less
- src/ui/views/ImportGnosisAddress/style.less
- fix: Field component
- fix: button gap
- fix: import overflow
> chore: fix some style

- src/ui/assets/icon-star-fill.svg
- src/ui/assets/icon-star.svg
- src/ui/assets/star-1.svg
- src/ui/component/Contact/EditModal.tsx
- src/ui/models/permission.ts
- src/ui/views/AddressDetail/AddressInfo.tsx
- src/ui/views/AddressDetail/style.less
- src/ui/views/AddressManagement/AddressItem.tsx
- src/ui/views/AddressManagement/index.tsx
- src/ui/views/AddressManagement/style.less
- src/ui/views/Dashboard/components/AddressRow.tsx
- src/ui/views/Dashboard/components/Contacts/ContactsItem.tsx
- src/ui/views/Dashboard/components/Contacts/index.tsx
- src/ui/views/Dashboard/components/RecentConnections/ConnectionItem.tsx
> chore: fix some bugs

- src/ui/component/QRCodeReader/index.tsx
> feat: + camera blur for QRCode base wallets

- src/background/controller/provider/rpcFlow.ts
- src/background/controller/wallet.ts
- src/background/index.ts
- src/background/utils/buildinProvider.ts
- src/ui/models/app.ts
- src/ui/utils/transaction.ts
- src/ui/views/Approval/components/SignText.tsx
- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/SignTypedData.tsx
- src/ui/views/Dashboard/components/AssetsList.tsx
- src/ui/views/Dashboard/components/ExtraLink/index.tsx
- src/ui/views/Dashboard/components/NFT/CollectionCard.tsx
- src/ui/views/Dashboard/components/NFT/NFTListRow.tsx
- src/ui/views/Dashboard/components/NFT/NFTModal.tsx
- src/ui/views/Dashboard/components/Security/index.tsx
- src/ui/views/Dashboard/components/TokenList.tsx
- src/ui/views/Dashboard/index.tsx
- src/ui/views/GnosisTransactionQueue/index.tsx
- src/ui/views/NFTApproval/components/NFTContractListItem.tsx
- src/ui/views/NFTApproval/components/NFTList.tsx
- src/ui/views/NFTApproval/index.tsx
- src/ui/views/Receive/index.tsx
- src/ui/views/SendNFT/index.tsx
- src/ui/views/SendToken/index.tsx
- src/ui/views/TokenApproval/components/ApprovalCard.tsx
- src/ui/views/TransactionHistory/index.tsx
- src/utils/transaction.ts
- fix: viewAssets
- feat: add signText ga event
- fix: receive ga
- fix: ga account category
- fix: enable
- fix: ga chain name
- fix: ga send & security
- fix: receive -1
- fix: viewasset
> fix: ga event

- _raw/manifest.json
- package.json
- src/background/service/keyring/eth-onekey-keyring.ts
- src/ui/views/Approval/components/SignTx.tsx
- yarn.lock
fixed https://github.com/RabbyHub/Rabby/issues/815
> feat: use OneKey SDK for OneKey hardware wallet

- src/background/controller/provider/rpcFlow.ts
- src/background/controller/wallet.ts
- src/background/index.ts
- src/background/service/notification.ts
- src/ui/views/Approval/components/LedgerHardwareWaiting.tsx
- src/ui/views/Dashboard/components/PendingApproval.tsx
- src/ui/views/Dashboard/index.tsx
- src/ui/views/SortHat.tsx
> Revert "revert code of sign queue"

- src/ui/index.tsx
> Revert "fix: adjust zoom when page zoom is not 1. fix #771"

- src/background/service/notification.ts
doc: https://debankglobal.larksuite.com/wiki/wikusWFn1n0eHzCPhMiMt22ftjd
> fix: only transaction or text request will keep in approval queue

- src/background/service/notification.ts
> fix: popup will be auto reject in linux

- src/background/controller/provider/rpcFlow.ts
- src/background/webapi/window.ts
https://debankglobal.larksuite.com/docs/docusTbV6t0OIoZi3eN3Meb7WIf
> feat: new height logic for notification window

- package.json
- yarn.lock
https://github.com/DeBankDeFi/fe-common/commit/be78812db001baf6d78ad68c79ca7349d60a6e65
> fix: celo use wrong native token address

- src/ui/component/WordsMatrix/MnemonicsInputs.tsx
> fix: Cursor jumps on seed phrase import

- src/background/controller/provider/controller.ts
- src/background/controller/provider/rpcFlow.ts
- src/ui/views/Approval/components/SignText.tsx
- src/utils/index.ts
> fix: compatible with wrong personal_sign params order

- src/ui/component/ChainSelector/style.less
- src/ui/component/ChainSelector/tag.tsx
- src/ui/views/NFTApproval/index.tsx
- src/ui/views/SendNFT/index.tsx
- src/ui/views/SendToken/index.tsx
- src/ui/views/Swap/index.tsx
- src/ui/views/TokenApproval/index.tsx
> fix: width issue of TagChainSelector

- src/background/service/keyring/eth-ledger-bridge-keyring.ts
https://sentry.io/organizations/debank/issues/3613186941/?project=5831390&query=is%3Aunresolved
> fix: can not use ledger deploy contract

- package.json
- src/background/controller/wallet.ts
- src/background/service/notification.ts
- src/background/service/transactionHistory.ts
- src/ui/utils/hooks.ts
- src/ui/views/Approval/components/LedgerHardwareWaiting.tsx
- src/ui/views/Approval/components/QRHardWareWaiting/QRHardWareWaiting.tsx
- src/ui/views/Approval/components/WatchAddressWaiting.tsx
- yarn.lock
1. use uuid as approvalId to prevent same approvalId
2. use approvalId as lock when resolve approval in 2-step approval for idempotent
> fix: approval queue

- package.json
- src/ui/views/ImportGnosisAddress/index.tsx
- yarn.lock
FYI: https://github.com/RabbyHub/gnosis-sdk/pull/2
> chore: safe api migration

- src/constant/index.ts
- src/ui/component/FallbackSiteLogo/index.tsx
- src/utils/index.ts
prevent Chrome interception since Rabby use website logo
> fix: + external resource blacklist to prevent warning from chrome

- src/utils/index.ts
> fix: catch invalid url

- package.json
- src/background/controller/provider/controller.ts
- src/background/controller/wallet.ts
- src/background/index.ts
- src/background/service/index.ts
- src/background/service/notification.ts
- src/background/service/rpc.ts
- src/ui/assets/custom-rpc/delete.svg
- src/ui/assets/custom-rpc/edit.svg
- src/ui/assets/dashboard/custom-rpc.svg
- src/ui/component/ChainIcon.tsx
- src/ui/component/ChainSelector/Modal.tsx
- src/ui/component/ChainSelector/index.tsx
- src/ui/models/customRPC.ts
- src/ui/models/index.ts
- src/ui/utils/token.ts
- src/ui/utils/url.ts
- src/ui/views/Approval/components/AddChain.tsx
- src/ui/views/Approval/style.less
- src/ui/views/CustomRPC/components/EditRPCModal.tsx
- src/ui/views/CustomRPC/index.tsx
- src/ui/views/CustomRPC/style.less
- src/ui/views/Dashboard/components/Settings/index.tsx
- src/ui/views/Dashboard/index.tsx
- src/ui/views/DexSwap/hooks.tsx
- src/ui/views/MainRoute.tsx
- src/ui/views/SendNFT/index.tsx
- src/ui/views/SendToken/index.tsx
- yarn.lock
> feat: custom rpc

- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/TxComponents/GasSelecter.tsx
- src/ui/views/Dashboard/components/Settings/index.tsx
- src/utils/transaction.ts
> feat: auto set maxPriorityFee

- src/background/controller/provider/controller.ts
fix the crashed prompt issue with https://www.convexfinance.com/claim
> fix: wallet_addEthereumChain params validation

- src/background/controller/provider/controller.ts
> feat: reject signTypedData if domain.chainId not same as connected chainId

- src/background/controller/provider/controller.ts
- src/background/service/transactionHistory.ts
- src/background/utils/tx.ts
- src/ui/views/Approval/components/SignTx.tsx
> fix: use local tx as response when eth_getTransactionByHash get a pending tx

- src/ui/views/Approval/components/PermitSignTypedData.tsx
- src/ui/views/Approval/components/SignTypedData.tsx
- src/ui/views/Approval/components/TxComponents/Approve.tsx
- src/ui/views/Approval/components/TxComponents/ApproveToken.tsx
- src/ui/views/Approval/components/TxComponents/Cancel.tsx
- src/ui/views/Approval/components/TxComponents/CancelNFT.tsx
- src/ui/views/Approval/components/TxComponents/CancelNFTCollection.tsx
- src/ui/views/Approval/components/TxComponents/sendNFT.tsx
- src/ui/views/Dashboard/components/TokenDetailPopup/HistoryItem.tsx
- src/ui/views/Dashboard/components/TokenDetailPopup/TokenDetail.tsx
- src/ui/views/Dashboard/components/TokenDetailPopup/style.less
> feat: + open etherscan link for contracts

- src/ui/views/AddressManagement/AddressItem.tsx
- src/ui/views/AddressManagement/style.less
> feat: only highlight action block of AddressItem

- src/constant/index.ts
- src/ui/views/Approval/components/SignTx.tsx
> feat: change default gas ratio to 2

- src/background/controller/provider/controller.ts
- src/background/utils/tx.ts
fix https://github.com/ethers-io/ethers.js/issues/3926
> fix: return r s v for pending transactions

- package.json
- yarn.lock
https://github.com/RabbyHub/eth-walletconnect-keyring/commit/ab07ce92cb4017695bb5093fb2c7f984d40ac6e4
> chore: update eth-walletconnect-keyring

- package.json
- yarn.lock
> Revert "feat: update page-provider"

- src/ui/views/Dashboard/components/BalanceView/CurveView.tsx
> Revert "fix: adjust chart section"

- package.json
- src/ui/views/Approval/components/Actions/ApproveNFT.tsx
- src/ui/views/Approval/components/Actions/ApproveNFTCollection.tsx
- src/ui/views/Approval/components/Actions/TokenApprove.tsx
- src/ui/views/Approval/components/Actions/components/Table.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/NFTSpenderPopup.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/SpenderPopup.tsx
- src/ui/views/Approval/components/SecurityEngine/RuleDrawer.tsx
- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/TypedDataActions/BatchPermit2.tsx
- src/ui/views/Approval/components/TypedDataActions/BuyNFT.tsx
- src/ui/views/Approval/components/TypedDataActions/Permit.tsx
- src/ui/views/Approval/components/TypedDataActions/Permit2.tsx
- yarn.lock
https://github.com/RabbyHub/rabby-security-engine/pull/11
> feat: value tooltip

- build/webpack.pro.config.js
> fix: source-map

- docs/ui.md
Fixed grammar and typos in docs/ui.md file
> fix grammar and typos in ui file

- package.json
- yarn.lock
> Revert "chore: update rabby-wallet/rabby-swap"

- package.json
- src/content-script/index.ts
- yarn.lock
> Revert "feat: change inject provider"

- src/background/controller/provider/rpcFlow.ts
- src/background/service/permission.ts
- src/constant/index.ts
- src/ui/views/Approval/components/AddChain.tsx
- src/ui/views/Approval/components/Connect/SignTestnetPermission.tsx
- src/ui/views/Approval/components/Connect/index.tsx
- src/ui/views/Approval/components/ETHSign.tsx
- src/ui/views/Approval/components/SignText.tsx
- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/SignTypedData.tsx
- src/ui/views/Approval/hooks/useSignPermissionCheck.tsx
- src/ui/views/Approval/hooks/useTestnetCheck.tsx
- src/ui/views/Approval/style.less
- src/ui/views/Dashboard/components/Settings/index.tsx
- feat: add sign permission and testnet alert
- fix: tooltip
> feat: add sign permission and testnet alert

- _raw/locales/es/messages.json
- _raw/locales/index.json
I have added the Spanish translations following your instructions. (100% texts completed based on i18n Ally review)
I am a native Spanish speaker, but some texts could be subject to improvements. Anyway, I think it's a good starting point.
> feat: spanish translations

- package.json
- yarn.lock
resolve https://github.com/RabbyHub/Rabby/issues/1698
fix https://github.com/RabbyHub/Rabby/issues/1403
> feat: update bitbot02-api

- src/background/service/keyring/eth-ledger-bridge-keyring.ts
FYI: https://github.com/MetaMask/eth-ledger-bridge-keyring/blob/main/src/ledger-keyring.ts#L505
fix https://github.com/RabbyHub/Rabby/issues/1690
> fix: v value of text message for ledger

- _raw/locales/fr_FR/messages.json
- _raw/locales/index.json
French version with 100% manual translation and local verification.
> French version

- _raw/locales/ua_UA/messages.json
Fix words and grammar to fit the translation
> Ukrainian grammar fix

- _raw/locales/index.json
- _raw/locales/pt_BR/messages.json
Language Support for Brazilian Portuguese pt-BR for Rabby Wallet.
The order of the language was also changed, sorted by: Letter
> Add Language Support: pt-br

- src/ui/component/Progress/index.less
- src/ui/component/Progress/index.tsx
- src/ui/component/QRCodeReader/index.tsx
- src/ui/views/Approval/components/QRHardWareWaiting/Reader.tsx
- src/ui/views/ImportHardware/QRCodeConnect/index.tsx
- Add progress of scanning QR code.
- Fix delay of scanning.
> Fix Scanning

- _raw/locales/index.json
- _raw/locales/ru/messages.json
I'am happy to have a chance to contribute to my favorite wallet. The translation was done using AI and carefully checked manually by a native speaker.
> Add Russian translation

- src/ui/component/NameAndAddress/index.tsx
- src/ui/utils/clipboard.tsx
resolve https://github.com/RabbyHub/Rabby/issues/1428 https://github.com/RabbyHub/Rabby/issues/1245
> feat: copy checksum address

- package.json
- yarn.lock
- Add Mode Sepolia Testnet
- Add Immutable zkEVM Testnet
- Remove Palm, Shiden, Taiko Grimsvotn L2 Testnet and Taiko Eldfell L3 Testnet
> feat: add new testnets

- src/ui/assets/approval/edit-arrow-right.svg
- src/ui/component/Popup/index.less
- src/ui/views/Approval/components/Actions/components/LogoWithText.tsx
- src/ui/views/Approval/components/Actions/components/NFTWithName.tsx
- src/ui/views/Approval/components/Actions/components/Table.tsx
- src/ui/views/Approval/components/Actions/components/ViewMore.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/CollectionPopup.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/NFTPopup.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/NFTSpenderPopup.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/ReceiverPopup.tsx
- src/ui/views/Approval/components/Actions/components/ViewMorePopup/SpenderPopup.tsx
- src/ui/views/Approval/components/Actions/index.tsx
- src/ui/views/Approval/components/BroadcastMode/index.tsx
- src/ui/views/Approval/components/TxComponents/BalanceChange.tsx
- src/ui/views/Approval/components/TxComponents/GasSelecter.tsx
- src/ui/views/Approval/style.less
> style: partial support dark mode.

- package.json
- src/background/service/keyring/eth-onekey-keyring.ts
- yarn.lock
https://github.com/RabbyHub/eth-trezor-keyring/pull/6/files
> fix: account details for trezor and onekey

- _raw/locales/fr_FR/messages.json
> fix: french typo

- docs/content-script.md
- docs/transaction.md
- docs/ui.md
Hi, found out few errors while reading the docs, tried to fix them as best as I could, please give any feedback
> docs: typo and grammar fix

- src/background/controller/wallet.ts
- src/background/service/keyring/eth-imkey-keyring.ts
- src/background/service/keyring/eth-ledger-bridge-keyring.ts
- src/background/service/keyring/index.ts
- src/background/service/preference.ts
- src/ui/component/ConnectStatus/useLedgerStatus.ts
- src/ui/views/Approval/components/LedgerHardwareWaiting.tsx
- src/ui/views/Approval/components/SignText.tsx
- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/SignTypedData.tsx
- remove iframe(ledger live bridge)
- remove `hdkey` and get the address from the device instead
- use signHelper to implement resend tx
> refactor: ledger keyring

- package.json
- yarn.lock
> chore: update trezor sdk

- src/ui/views/Approval/components/CommonAction.tsx
> fix: show send eth amount on common actions

- src/ui/views/Approval/components/CommonAction.tsx
> Revert "feat: rm alert in common actions"

- README.md
- docs/content-script.md
- docs/translation.md
[x] using relative links in markdown files
[x] fixing a typo
> chore: use relative links

- _raw/sw.js
- package.json
- src/background/service/notification.ts
- src/background/service/transactionHistory.ts
- src/background/utils/rpcCache.ts
- src/content-script/index.ts
- src/manifest/mv3/manifest.json
- src/offscreen/scripts/offscreen.ts
- yarn.lock
- An extension cannot have more than 500 active alarms. [refer](https://debank.sentry.io/issues/5088602961/?project=5831390&query=release%3A0.92.56&referrer=release-issue-stream)
- Using settimtout instead of alarm.
- Cannot read properties of undefined (reading 'hasDocument') [refer](https://debank.sentry.io/issues/5088593173/?project=5831390&query=release%3A0.92.56&referrer=release-issue-stream)
- chrome version less than 109 does not support offscreen api.
- Error in invocation of action.setBadgeText(object details, optional function callback): Error at parameter 'details': Missing required property 'text'. [refer](https://debank.sentry.io/issues/5088596290/?project=5831390&query=release%3A0.92.56&referrer=release-issue-stream)
- The …
> fix: bugs in mv3

- src/ui/views/HDManager/AccountList.tsx
- src/ui/views/HDManager/utils.tsx
> Revert "feat: get address balances one by one on the address management page"

- package.json
- yarn.lock
https://github.com/RabbyHub/eth-walletconnect-keyring/commit/6d89533b76175516e23e120c289452320d306cce
> fix: parse account in walletconnect, close #2165

- package.json
- yarn.lock
https://github.com/RabbyHub/eth-walletconnect-keyring/pull/11
> fix: sometimes the wc qr code can't appear

- _raw/locales/en/messages.json
- src/background/controller/wallet.ts
- src/background/service/permission.ts
- src/ui/models/permission.ts
- src/ui/style/antd-overwrite.less
- src/ui/views/CustomRPC/components/EditRPCModal.tsx
- src/ui/views/Dashboard/components/CurrentConnection/index.tsx
- src/ui/views/Dashboard/components/CurrentConnection/style.less
- src/ui/views/Dashboard/components/RecentConnections/ConnectionItem.tsx
- src/ui/views/Dashboard/components/RecentConnections/ConnectionList.tsx
- src/ui/views/Dashboard/components/RecentConnections/index.tsx
- src/ui/views/Dashboard/components/RecentConnections/style.less
- src/ui/views/History/style.less
- feat: hide dapp search
- feat: support pin connected site
> feat: hide dapp search

- patches/@debank+common+0.3.60.patch
- src/background/service/customTestnet.ts
- src/ui/views/SendToken/index.tsx
- src/utils/chain.ts
---
- don't pass `params.gas` if no estimated gas queried on Send UI
> fix: native token estimated gas.

- package.json
- yarn.lock
https://github.com/RabbyHub/eth-lattice-keyring/commit/c503fac4fb2946196c80703c1ddefa94eefb412f
> fix: lattice-keyring remove window.fetch

- package.json
- src/ui/views/Approval/components/Actions/AssetOrder.tsx
- src/ui/views/Approval/components/Actions/utils.tsx
- src/ui/views/Approval/components/TypedDataActions/utils.ts
- yarn.lock
related: https://github.com/RabbyHub/rabby-security-engine/pull/23
> feat: + rule for assetOrder has no receive assets

- _raw/locales/en/messages.json
- src/background/controller/wallet.ts
- src/background/service/preference.ts
- src/ui/models/preference.ts
- src/ui/views/SendToken/components/SwitchReserveGas.tsx
- src/ui/views/SendToken/index.tsx
> feat: allow user determine if reverse gas.

- _raw/locales/ru/messages.json
Small language fixes. JSON validated.
> Update RU messages.json

- _raw/locales/en/messages.json
- src/ui/component/Contact/EditModal.tsx
- src/ui/utils/confirmPopup.less
- src/ui/utils/useRepeatImportConfirm.tsx
- src/ui/views/AddressBackup/PrivateKey.tsx
- src/ui/views/AddressBackup/style.less
- src/ui/views/Approval/components/FooterBar/AccountInfo.tsx
- src/ui/views/Approval/components/FooterBar/CommonAccount.tsx
- src/ui/views/CustomRPC/index.tsx
- src/ui/views/PreferMetamaskDapps/style.less
- src/ui/views/SendToken/style.less
> feat: ui bugs

- _raw/locales/zh-HK/messages.json
> docs: translate zh-HK

- package.json
- src/ui/views/Approval/components/Actions/utils.tsx
- src/ui/views/Approval/components/TxComponents/GasSelectorHeader.tsx
- yarn.lock
https://github.com/RabbyHub/rabby-security-engine/pull/25
> fix: skip 1118 rule check in mnt

- package.json
- src/ui/views/Approval/components/Actions/ApproveNFT.tsx
- src/ui/views/Approval/components/Actions/ApproveNFTCollection.tsx
- src/ui/views/Approval/components/Actions/TokenApprove.tsx
- src/ui/views/Approval/components/TypedDataActions/BatchPermit2.tsx
- src/ui/views/Approval/components/TypedDataActions/Permit.tsx
- src/ui/views/Approval/components/TypedDataActions/Permit2.tsx
- yarn.lock
https://github.com/RabbyHub/rabby-security-engine/pull/26
> feat: rule for trust value is zero

- _raw/sw.js
- src/content-script/index.ts
- src/offscreen/scripts/offscreen.ts
> Revert "feat: sw remove keep alive"

- src/background/service/openapi.ts
async init store to fix dev load bug
> fix: async init store to fix dev load bug

- package.json
- src/ui/views/HDManager/OnekeyManager.tsx
- yarn.lock
https://github.com/RabbyHub/eth-trezor-keyring/pull/11
> fix: get path for old trezor account

- src/ui/views/Approval/components/TxComponents/BalanceChange.tsx
> fix: overflow display of token in balance change

- package.json
- src/ui/utils/sendTransaction.ts
- src/ui/views/Approval/components/MiniSignTx/index.tsx
- src/ui/views/Approval/components/SignTestnetTx/index.tsx
- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/TxComponents/GasSelectorHeader.tsx
- src/ui/views/Dashboard/components/GasPriceBar/index.tsx
- src/ui/views/Ecology/dbk-chain/pages/Bridge/hooks/useDbkChainBridge.ts
- src/ui/views/SendToken/index.tsx
- src/ui/views/Swap/hooks/quote.tsx
- src/ui/views/Swap/hooks/token.tsx
- src/ui/views/TransactionHistory/components/SkipNonceAlert.tsx
- src/ui/views/TransactionHistory/components/TransactionItem.tsx
- yarn.lock
> Revert "feat: update gasMarket api"

- src/ui/utils/number.ts
> feat: optimize scientific notation

- package.json
- src/background/service/notification.ts
- src/utils/message/index.ts
- yarn.lock
- fix: message channel
- fix: page-provider conflict
> fix: page-provider conflict

- _raw/sw.js
- src/content-script/index.ts
> fix: page-provider inject order

- _raw/locales/fr-FR/messages.json
Hi guys,
Just pushed a little update for FR language (mainly wording, UI fixes + missing texts).
> FR translations update

- src/ui/views/Approval/components/SignTx.tsx
- src/ui/views/Approval/components/TxComponents/SafeNonceSelector.tsx
> fix: wrong safe nonce recommend

- package.json
- src/ui/component/WalletConnect/useWalletConnectIcon.ts
- src/utils/walletconnect.ts
- yarn.lock
https://github.com/RabbyHub/eth-walletconnect-keyring/commit/e788d31bdeb5c2e6bd728f72a777ff42d2accca4
> fix: switch all to walletconnect v2

- src/background/service/uninstalled.ts
https://github.com/RabbyHub/rabby.io/pull/94/files
> feat: add version to uninstall page

- src/background/service/customTestnet.ts
fixes: https://github.com/RabbyHub/Rabby/issues/2860
> folow spec and ensure params is defined

- src/background/controller/provider/controller.ts
> fix: repeat rpc error for intergrated network

- src/ui/views/CommonPopup/AssetList/ChainItem.tsx
- src/ui/views/CommonPopup/AssetList/TestnetChainList.tsx
- src/ui/views/SendToken/components/ModalConfirmAddToContacts.tsx
Improves user experience by:
- Adding hover effects to chain filter items for better visual feedback.
- Enhancing the address display in the add contact modal for improved readability and copy functionality.
> Enhances UI with hover states and address display

- package.json
- src/ui/component/AccountSelector/AccountItem.tsx
- src/ui/component/TokenAmountInput/index.tsx
- src/ui/component/TokenSelector/index.tsx
- src/ui/hooks/useAddressInfo.ts
- src/ui/hooks/useAddressRisk.ts
- src/ui/hooks/useSearchTestnetToken.ts
- src/ui/utils/useRepeatImportConfirm.tsx
- src/ui/views/SendPoly/index.tsx
- src/ui/views/SendToken/index.tsx
- src/ui/views/SendToken/useInitCheck.ts
- src/ui/views/WhitelistInput/index.tsx
- yarn.lock
1. fix some ui bugs 
2. check the recommend token when enter Send page
> fix: ui & recommend token for cex or contract ddress

- src/background/controller/provider/controller.ts
ref: https://github.com/ethereum/web3.py/pull/3216
> fix: ignore transaction indexing is in progress error
