src/background/service/preference.ts
To avoid a non-chinese user use Chinese as default locale since some wired config
FYI #349
=> fix: make defaultLocale as english no matter what language is accepted

src/ui/component/AddressList/index.tsx
1. Sometimes when import Ledger address will create 2 duplicate keyrings, this will make address duplication
2. Private keyring is independent means when we import via pk will create new keyring every time which will cause order issue
=> fix: address duplication in address list

package.json, src/background/controller/wallet.ts, src/ui/component/AddressList/AddressItem.tsx, src/ui/component/AddressList/index.tsx, src/ui/component/AddressViewer/index.tsx, src/ui/component/MultiSelectAddressList.tsx, src/ui/views/AddressManagement/index.tsx, src/ui/views/Approval/components/WatchAdrressWaiting.tsx, src/ui/views/Approval/style.less, src/ui/views/Dashboard/index.tsx, src/ui/views/Dashboard/style.less, src/ui/views/ImportSuccess/index.tsx, src/ui/views/SelectAddress/index.tsx, yarn.lock
By using the infinity loader, there are several problems may difficult to solve:
1. Can not exactly point to specific number, as the list get longer, the  position to the right number may much higher.
2. By input number or scroll the select address page, there may some lag for user experience.
3. If already to a specific number, scrolling back, the loading skeleton is still there, and  other bad user experience.
Therefore, I prefer to use react-window here.
Demo:
https://user-images.githubusercontent.com/12989352/144710059-a114f62b-623c-432c-ba24-c20b15d47a44.mov
Need discuss :
Previously, I found through ledger live, no addresses can see, it's an exist problem in production,  which is iframe been blocked.  AKA, we may need some words or reminder for users if their ledger needs passwords …
=> feat: still use react window, add load locker

src/ui/component/ChainCard/index.tsx, src/ui/component/ChainSelector/Modal.tsx, src/ui/component/ChainSelector/style.less
Found that when scrolling right in the chain selector modal there is a useless gap and try to fix it
=> fix: overflow issue of chain selector modal

package.json, yarn.lock
This allows the BitBox02 to directly accept a network chain ID, which
allows future network additions to happen without changes to the JS
library.
BitBox02 v9.10.0 (out soon) will add support for Binance Smart Chain, Optimism, Polygon and Arbitrum One.
=> package.json: bump the bitbox02 dep to v0.14.0

src/background/utils/persisitStore.ts
The line below overwrites the assignment in this condition, so the created proxy is never actually used.
=> Remove dead code

package.json, src/background/service/keyring/eth-bitbox02-keyring.ts, yarn.lock
BitBox02 firmware v9.12.0 is needed.
=> bitbox02: add support for signing EIP-712 typed data

src/background/controller/provider/controller.ts
Wallet no need to unlock before eth_accounts requested, but will response an empty account list
=> fix: eth_accounts no need permission

src/background/service/keyring/eth-bitbox02-keyring.ts, src/ui/views/SelectAddress/index.tsx
The bitbox2 only supports up to 100 accounts. We don't need to store the keypath, just prevent importing accounts that exceed the index. 
https://github.com/digitalbitbox/bitbox02-firmware/blob/d37474e37f6715de42094b78396677c1264da10e/src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs#L21
https://github.com/digitalbitbox/bitbox02-firmware/blob/d37474e37f6715de42094b78396677c1264da10e/src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs#L68-L80
=> fix: bitbox2 supports up to 100 accounts close #1048, close #1026

package.json, src/background/index.ts, yarn.lock
https://thena.fi/ not work well with rabby subscription api. 
The reason is that version 1.2.1 of web3.js was used, which implemented subscriptions via the data event. However, the data event has been deprecated and replaced with the message event. 
To make it work, compatibility was added here.
=> feat: support deprecated data event

src/constant/index.ts
Rabby's Gas Estimation logic uses a buffer of 1.5x on all networks except for Moonbeam where it uses a buffer of 2 as a SAFE_GAS_LIMIT_RATIO. Moonriver network is architecturally identical to Moonriver network (it is the sister network of Moonbeam) so it should also use this same safe gas limit ratio. 
We noticed this issue because a user reported an issue where certain revoke staking transactions were failing due to low gas limits. This error was not faced in MetaMask, and it was not faced when using Rabbi on the Moonbeam Network. As a matter of good practice I am including Moonbase Alpha (the testnet for both Moonriver and Moonbeam) in this PR, however it may not be strictly necessary. I did not notice the same issue on Moonbase Alpha but logically it makes sense to keep this …
=> fix Moonriver and Moonbase Alpha gas limit Issue

src/ui/views/Approval/components/QRHardWareWaiting/Player.tsx
Hi Rabby Team!
This PR introduces a change to the density of the animated QR codes so that they can be scanned by the ZERO hardware wallet from NGRAVE.
This MR is the same change as implemented in MetaMask: https://github.com/MetaMask/metamask-extension/pull/22135
=> Decreased UR density

build/webpack.common.config.js, package.json, src/background/service/keyring/eth-bitbox02-keyring.ts, yarn.lock
The previous one (bitbox02-api) is being deprecated.
The new one is much smaller in size, comes with complete TypeScript, and is a proper ES6 module. It is based on WASM, which is why `asyncWebAssembly: true` needs to be set.
=> bitbox02: switch to new bitbox client library

package.json, yarn.lock
It fixes a parsing bug when signing typed messages that contain "0x1" or other uneven hex strings for uints.
=> bitbox02: bump bitbox-api to v0.3.2

_raw/locales/index.json, _raw/locales/zh_HK/messages.json
Description:
Add Traditional Chinese language support in locales
Changes:
1. Add file `zh-HK` (Traditional Chinese) language in `_raw/locales` folder
2. Add zh_HK in `index.json` [locales index](https://github.com/RabbyHub/Rabby/blob/develop/_raw/locales/index.json)
Comment:
As a native speaker of Traditional Chinese, I have reviewed all translations to ensure their accuracy.
The Traditional Chinese (`zh-HK`) language is translated based on Simplified Chinese (`zh-CN`) text to do the localizations
=> feat(locales): add traditional chinese i18n support

src/background/controller/wallet.ts
When removing an address/account, the walletconnect connector needs to be killed.
=> kill walletconnect connector when removing address

package.json, src/ui/views/Approval/components/QRHardWareWaiting/Player.tsx
Hi Team, 
This PR is a copy of one recently merged for MetaMask: https://github.com/MetaMask/metamask-extension/pull/24952
We noticed differences in density, i.e. QR version number, between the animated QR codes generated by the MetaMask extension and the MetaMask mobile app.
In essence, we discovered several issues with a subdependency in the currently used version of `qrcode.react`: `qr.js` which is used to generate the QR images. Please see the above linked PR at MetaMask for full details. 
To address the potential security risk and the irregular QR codes generated by the defunct dependency, it suffices to increase the version number of qrcode.react to the latest version.
Additionally, We also propose to increase the QR code image size to 250px, reflecting the size used with MetaMask …
=> Update defunct, potentially risky QR dependency & Increase QR size

src/ui/component/Tooltip/TooltipWithMagnetArrow.tsx, src/ui/views/Approval/components/Actions/ContractCall.tsx, src/ui/views/Approval/components/Actions/components/SubTable.tsx, src/ui/views/Approval/components/Actions/components/Table.tsx, src/ui/views/Approval/components/Actions/components/Values.tsx, src/ui/views/Approval/components/Actions/index.tsx, src/ui/views/Approval/components/AddAsset.tsx, src/ui/views/Approval/components/BroadcastMode/index.tsx, src/ui/views/Approval/components/FooterBar/GasLessComponents.tsx, src/ui/views/Approval/components/FooterBar/ProcessActions.tsx, src/ui/views/Approval/components/OriginInfo.tsx, src/ui/views/Approval/components/SecurityEngine/RuleDrawer.backup.tsx, src/ui/views/Approval/components/SecurityEngine/RuleDrawer.tsx, src/ui/views/Approval/components/SignTestnetTx/components/TestnetActions.tsx, src/ui/views/Approval/components/TextActions/index.tsx, src/ui/views/Approval/components/TxComponents/GasSelecter.tsx, src/ui/views/Approval/components/TxComponents/GasSelectorHeader.tsx, src/ui/views/Approval/components/TypedDataActions/ContractCall.tsx, src/ui/views/Approval/components/TypedDataActions/index.tsx
=> feat: tooltip within an approval page will appear in a container with padding

package.json, src/content-script/index.ts, yarn.lock
https://github.com/RabbyHub/page-provider/pull/48
=> fix: execute tabCheckIn on content-script connection.

src/utils/transaction.ts
The problem in #2710 still exists after new release, so I've double checked the changes introduced in #2726 and noticed that the safe buffer only applies when the recommended gas limit is strictly greater than the block gas limit. However, there can be scenarios—such as an estimated gas limit of 59M against a block limit of 60M—where the buffer isn't applied, even though it might still be necessary. For example, Bifrost chain allows only 86% of the block gas limit for a single transaction, meaning a 59M gas estimate could actually fail if the block limit is 60M. It might be beneficial to adjust the logic to account for this by checking whether the recommended gas limit exceeds the (block gas limit * safe buffer ratio) instead.
=> fix: gas limit issue in testnet

src/ui/views/AddressBackup/PrivateKey.tsx, src/ui/views/AddressBackup/style.less
This PR enables copying a wallet's private key without revealing it on screen. Useful for handling keys discreetly.
The copy button is now always visible. The width of the "Click to show" area has been reduced to remove overlap, to avoid accidental key exposure when clicking the copy button.
=> feat: allow copying wallet PK without displaying it
